[project]
name = "cora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.2",
    "pyttsx3>=2.99",
    "speechrecognition>=3.14.5",
    "wikipedia>=1.4.0",
]
